<?php

namespace Models\Common;

class MemberStatement extends BaseModel
{
    protected $connection    = 'mysql_aggregated';
    protected $table         = 'statement';
    protected $hasPrimaryKey = false;

    public function getList( $where = [] , $orWhere = [] , $whereIn = [] , $pageCount = 18 )
    {
        $this->listColumn = [
            'date',
            'uid',
            \DB::raw ( 'SUM(bet) as bet' ) ,
            \DB::raw ( 'SUM(win_lose) as win_lose' ) ,
            \DB::raw ( 'SUM(gross_comm) as gross_comm' ) ,
            \DB::raw ( 'SUM(cash_transfer) as cash_transfer' ) ,
        ];

        $this->groupBy = [
            'uid'
        ];

        return parent::getList ( $where , $orWhere , $whereIn , $pageCount ); // TODO: Change the autogenerated stub
    }
}